title: 'Silke K. Kaiser'
description: 'PhD Student in Machine Learning and Sustainable Transport'

name: 'Silke K. Kaiser'
url: https://silkekaiser.github.io

theme: jekyll-theme-cayman

github_username:      silkekaiser


 [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/USERNAME"

 [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/USERNAME"

 [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/USERNAME"

  [[params.social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.co.in/citations?user=USERID"  

